config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :turnips


  resources :items do
    collection {post :import}
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "items#index"

  get 'items/index'

  get 'items/import', to: 'itmes#my_import'
  get '/houseware', to: 'items#houseware'
  get '/wall-mounted', to: 'items#wall_mounted'
  get '/wallpapers', to: 'items#wallpaper'
  get '/floors', to: 'items#floor'
  get '/rugs', to: 'itmes#rug'
  get '/fencing', to: 'items#fencing'
  get '/photos', to: 'items#photo'
  get '/posters', to: 'items#poster'
  get '/tools', to: 'items#tool'
  get '/tops', to: 'items#clothes_top'
  get '/bottoms', to: 'items#clothes_bottom'
  get '/dresses', to: 'items#clothes_dresse'
  get '/headware', to: 'items#headware'
  get '/accessories', to: 'items#accessories'
  get '/socks', to: 'items#sock'
  get '/shoes', to: 'items#shoe'
  get '/bags', to: 'items#bag'
  get '/umbrellas', to: 'items#umbrella'
  get '/music', to: 'items#music'
  get '/artwork', to: 'items#art'

  get '/wall-mounted/:dt', to: 'items#wall_mounted'
end

app/views/shared/_main_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">ACTools</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link"><%= link_to 'items', items_path, method: :get %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Items
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a><%= link_to 'Shoes', shoes_path %></a>
          <a class="dropdown-item" href=" <%= wall_mounted_url %>">Wall Mounted Stuff</a>
          <a class="dropdown-item" href=" <%= wallpapers_path %>">Wallpapers</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>

  </div>
</nav>