config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :turnips


  resources :items do
    collection {post :import}
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "items#index"

  get 'items/index'

  get 'items/import', to: 'itmes#my_import'
  get '/houseware', to: 'items#houseware'
  get '/wall-mounted', to: 'items#wall_mounted'
  get '/wallpapers', to: 'items#wallpaper'
  get '/floors', to: 'items#floor'
  get '/rugs', to: 'itmes#rug'
  get '/fencing', to: 'items#fencing'
  get '/photos', to: 'items#photo'
  get '/posters', to: 'items#poster'
  get '/tools', to: 'items#tool'
  get '/tops', to: 'items#clothes_top'
  get '/bottoms', to: 'items#clothes_bottom'
  get '/dresses', to: 'items#clothes_dresse'
  get '/headware', to: 'items#headware'
  get '/accessories', to: 'items#accessories'
  get '/socks', to: 'items#sock'
  get '/shoes', to: 'items#shoe'
  get '/bags', to: 'items#bag'
  get '/umbrellas', to: 'items#umbrella'
  get '/music', to: 'items#music'
  get '/artwork', to: 'items#art'

  get '/wall-mounted/:dt', to: 'items#wall_mounted'
end

app/models/turnip.rb
class Turnip < ApplicationRecord
end

app/controllers/turnips_controller.rb
class TurnipsController < ApplicationController
  before_action :set_turnip, only: [:show, :edit, :update, :destroy]

  # GET /turnips
  # GET /turnips.json
  def index
    @turnips = Turnip.all
  end

  # GET /turnips/1
  # GET /turnips/1.json
  def show

  end

  def calc_spent(amount, cost)
    @bells_spent = amount * cost
    puts @bells_spent
    return @bells_spent
  end
  helper_method :calc_spent

  def calc_total(amount, saleprice)
    @bells_total = amount * saleprice
    puts @bells_total
    return @bells_total
  end
  helper_method :calc_total

  # GET /turnips/new
  def new
    @turnip = Turnip.new
  end

  # GET /turnips/1/edit
  def edit
  end

  # POST /turnips
  # POST /turnips.json
  def create
    @turnip = Turnip.new(turnip_params)

    respond_to do |format|
      if @turnip.save
        format.html { redirect_to @turnip, notice: 'Turnip was successfully created.' }
        format.json { render :show, status: :created, location: @turnip }
      else
        format.html { render :new }
        format.json { render json: @turnip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turnips/1
  # PATCH/PUT /turnips/1.json
  def update
    respond_to do |format|
      if @turnip.update(turnip_params)
        format.html { redirect_to @turnip, notice: 'Turnip was successfully updated.' }
        format.json { render :show, status: :ok, location: @turnip }
      else
        format.html { render :edit }
        format.json { render json: @turnip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turnips/1
  # DELETE /turnips/1.json
  def destroy
    @turnip.destroy
    respond_to do |format|
      format.html { redirect_to turnips_url, notice: 'Turnip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turnip
      @turnip = Turnip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turnip_params
      params.require(:turnip).permit(:purchasePrice, :amountPurchased, :salePrice, :spentBells, :madeBells, :week_of, :tap_link)
    end
end

app/helpers/turnips_helper.rb
module TurnipsHelper
end

app/views/turnips/_form.html.erb
<%= form_with(model: turnip, local: true) do |form| %>
  <% if turnip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turnip.errors.count, "error") %> prohibited this turnip from being saved:</h2>

      <ul>
        <% turnip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :purchasePrice %>
    <%= form.text_field :purchasePrice %>
  </div>

  <div class="field">
    <%= form.label :amountPurchased %>
    <%= form.text_field :amountPurchased %>
  </div>

  <div class="field">
    <%= form.label :salePrice %>
    <%= form.text_field :salePrice %>
  </div>

  <div class="field">
    <%= form.label :spentBells %>
    <%= form.text_field :spentBells %>
  </div>

  <div class="field">
    <%= form.label :madeBells %>
    <%= form.text_field :madeBells %>
  </div>

  <div class="field">
    <%= form.label :week_of %>
    <%= form.date_field :week_of %>
  </div>

  <div class="field">
    <%= form.label :tap_Link %>
    <%= form.text_field :tap_link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/turnips/edit.html.erb
<h1>Editing Turnip</h1>

<%= render 'form', turnip: @turnip %>

<%= link_to 'Show', @turnip %> |
<%= link_to 'Back', turnips_path %>

app/views/turnips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turnips</h1>

<table>
  <thead>
    <tr>
      <th>Week Of</th>
      <th>Purchaseprice</th>
      <th>Amountpurchased</th>
      <th>Saleprice</th>
      <th>Spentbells</th>
      <th>Madebells</th>
      <th>TAP Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turnips.each do |turnip| %>
      <tr>
        <td><%= turnip.week_of %></td>
        <td><%= turnip.purchasePrice %></td>
        <td><%= turnip.amountPurchased %></td>
        <td><%= turnip.salePrice %></td>
        <td><%= turnip.spentBells %></td>
        <td><%= turnip.madeBells %></td>
        <td><%= turnip.tap_link %></td>
        <td><%= link_to 'Show', turnip %></td>
        <td><%= link_to 'Edit', edit_turnip_path(turnip) %></td>
        <td><%= link_to 'Destroy', turnip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turnip', new_turnip_path %>

app/views/turnips/new.html.erb
<h1>New Turnip</h1>

<%= render 'form', turnip: @turnip %>

<%= link_to 'Back', turnips_path %>

app/views/turnips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Week Of:</strong>
  <%= @turnip.week_of %>
</p>

<p>
  <strong>Purchaseprice:</strong>
  <%= @turnip.purchasePrice %>
</p>

<p>
  <strong>Amountpurchased:</strong>
  <%= @turnip.amountPurchased %>
</p>

<p>
  <strong>Saleprice:</strong>
  <%= @turnip.salePrice %>
</p>

<p>
  <strong>Spentbells:</strong>
  <%= @turnip.spentBells %>
</p>

<p>
  <strong>Madebells:</strong>
  <%= @turnip.madeBells %>
</p>
<p>
  <strong>Bells Spent on Turnips:</strong>
<%= calc_spent(@turnip.amountPurchased, @turnip.purchasePrice) %>
</p>

<p>
  <strong>Total bells made:</strong>
<%= calc_total(@turnip.amountPurchased, @turnip.salePrice) %>
</p>

<p>
<strong>Total bells profit (spent - made):</strong>
<%= calc_total(@turnip.amountPurchased, @turnip.salePrice) - calc_spent(@turnip.amountPurchased, @turnip.purchasePrice) %>
</p>

<p>
  <strong>turnipprophet.io link week end:</strong>
  <%= @turnip.tap_link %>
</p>


<%= link_to 'Edit', edit_turnip_path(@turnip) %> |
<%= link_to 'Back', turnips_path %>