config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :turnips


  resources :items do
    collection {post :import}
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "items#index"

  get 'items/index'

  get 'items/import', to: 'itmes#my_import'
  get '/houseware', to: 'items#houseware'
  get '/wall-mounted', to: 'items#wall_mounted'
  get '/wallpapers', to: 'items#wallpaper'
  get '/floors', to: 'items#floor'
  get '/rugs', to: 'itmes#rug'
  get '/fencing', to: 'items#fencing'
  get '/photos', to: 'items#photo'
  get '/posters', to: 'items#poster'
  get '/tools', to: 'items#tool'
  get '/tops', to: 'items#clothes_top'
  get '/bottoms', to: 'items#clothes_bottom'
  get '/dresses', to: 'items#clothes_dresse'
  get '/headware', to: 'items#headware'
  get '/accessories', to: 'items#accessories'
  get '/socks', to: 'items#sock'
  get '/shoes', to: 'items#shoe'
  get '/bags', to: 'items#bag'
  get '/umbrellas', to: 'items#umbrella'
  get '/music', to: 'items#music'
  get '/artwork', to: 'items#art'

  get '/wall-mounted/:dt', to: 'items#wall_mounted'
end

app/models/item.rb
class Item < ApplicationRecord
  validates :unique_entry_id, uniqueness: true

  require 'csv'
  require 'activerecord-import/base'

  def self.my_import(file)
    items = []
    CSV.foreach(file.path, headers: true, skip_blanks: true, header_converters: :symbol) do |row|
      items << Item.new(row.to_h)
    end
    Item.import items, recursive: true
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "wallpapers") }
    end
  end


  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Item.my_import(params[:file])
    redirect_to items_url, notice: "Successfully Imported Data!"
  end

  def wall_mounted
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "wall-mounted") }
    end
  end

  def wallpaper
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "wallpapers") }
    end
  end

  def floor
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "floors") }
    end
  end

  def rug
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "rugs") }
    end
  end

  def fencing
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "fencing") }
    end
  end

  def photo
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "photos") }
    end
  end

  def poster
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "posters") }
    end
  end

  def tool
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "tools") }
    end
  end

  def clothes_top
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "tops") }
    end
  end

  def clothes_bottom
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "bottoms") }
    end
  end

  def clothes_dresse
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "dresses") }
    end
  end

  def headware
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "headware") }
    end
  end

  def accessories
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "accessories") }
    end
  end

  def sock
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "sock") }
    end
  end

  def shoe
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "shoes") }
    end
  end

  def bag
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "bags") }
    end
  end

  def umbreslla
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "umbrellas") }
    end
  end

  def music
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "music") }
    end
  end

  def art
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, category: "art") }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :image, :variation, :body_title, :pattern, :pattern_title, :diy, :body_customize, :pattern_customize, :kit_cost, :buy, :sell, :color_1, :color_2, :size, :source, :source_notes, :version, :hha_concept_1, :hha_concept_2, :hha_series, :hha_set, :interact, :tag, :tag, :speaker_type, :lighting_type, :catalog, :filename, :variant_id, :internal_id, :door_deco, :vfx, :vfx_type, :window_type, :window_color, :pane_type, :curtain_type, :curtain_color, :ceiling_type, :set, :uses, :closet_image, :storage_image, :label_themes, :primary_shape, :secondary_shape, :framed_image, :album_image, :high_res_texture, :genuine, :category)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/art.html.erb
<h1>Wall Mounted Items</h1>

<div class="container">
<table id="wallitems-datatable" class="display table table-striped table-bordered" data-source="<%= artwork_path(format: :json) %>">

  <thead>
    <tr>
      <th>Expand</th>
      <th>Name</th>
      <th>Variation</th>
      <th>Buy</th>
      <th>Sell</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  </table>
<br></br>
</div>

app/views/items/bag.html.erb
<h1>Wall Mounted Items</h1>

<div class="container">
<table id="wallitems-datatable" class="display table table-striped table-bordered" data-source="<%= bags_path(format: :json) %>">

  <thead>
    <tr>
      <th>Expand</th>
      <th>Name</th>
      <th>Variation</th>
      <th>Buy</th>
      <th>Sell</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  </table>
<br></br>
</div>

app/views/items/clothes_dresse.html.erb
<h1>Wall Mounted Items</h1>

<div class="container">
<table id="wallitems-datatable" class="display table table-striped table-bordered" data-source="<%= dresses_path(format: :json) %>">

  <thead>
    <tr>
      <th>Expand</th>
      <th>Name</th>
      <th>Variation</th>
      <th>Buy</th>
      <th>Sell</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  </table>
<br></br>
</div>

app/views/items/fencing.html.erb
<h1>Wall Mounted Items</h1>

<div class="container">
<table id="wallitems-datatable" class="display table table-striped table-bordered" data-source="<%= fencing_path(format: :json) %>">

  <thead>
    <tr>
      <th>Expand</th>
      <th>Name</th>
      <th>Variation</th>
      <th>Buy</th>
      <th>Sell</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  </table>
<br></br>
</div>

app/views/items/floor.html.erb
<h1>Wall Mounted Items</h1>

<div class="container">
<table id="wallitems-datatable" class="display table table-striped table-bordered" data-source="<%= floors_path(format: :json) %>">

  <thead>
    <tr>
      <th>Expand</th>
      <th>Name</th>
      <th>Variation</th>
      <th>Buy</th>
      <th>Sell</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  </table>
<br></br>
</div>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1> import </h1>
<div>
  <h4> import data! </h4>
  <%= form_tag import_items_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "import file" %>
  <% end %>

<h1>Items</h1>

<div class="container">
<table id="items-datatable" class="display table table-striped table-bordered" data-source="<%= items_path(format: :json) %>">

  <thead>
    <tr>
      <th>Expand</th>
      <th>Name</th>
      <th>Variation</th>
      <th>Buy</th>
      <th>Sell</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  </table>
<br></br>
</div>




<%= link_to 'New Item', new_item_path %>

app/views/items/music.html.erb
<h1>Wall Mounted Items</h1>

<div class="container">
<table id="wallitems-datatable" class="display table table-striped table-bordered" data-source="<%= music_path(format: :json) %>">

  <thead>
    <tr>
      <th>Expand</th>
      <th>Name</th>
      <th>Variation</th>
      <th>Buy</th>
      <th>Sell</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  </table>
<br></br>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/poster.html.erb
<h1>Wall Mounted Items</h1>

<div class="container">
<table id="wallitems-datatable" class="display table table-striped table-bordered" data-source="<%= posters_path(format: :json) %>">

  <thead>
    <tr>
      <th>Expand</th>
      <th>Name</th>
      <th>Variation</th>
      <th>Buy</th>
      <th>Sell</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  </table>
<br></br>
</div>

app/views/items/shoe.html.erb
<h1>Wall Mounted Items</h1>

<div class="container">
<table id="wallitems-datatable" class="display table table-striped table-bordered" data-source="<%= shoes_path(format: :json) %>">

  <thead>
    <tr>
      <th>Expand</th>
      <th>Name</th>
      <th>Variation</th>
      <th>Buy</th>
      <th>Sell</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  </table>
<br></br>
</div>

app/views/items/tool.html.erb
<h1>Wall Mounted Items</h1>

<div class="container">
<table id="wallitems-datatable" class="display table table-striped table-bordered" data-source="<%= tools_path(format: :json) %>">

  <thead>
    <tr>
      <th>Expand</th>
      <th>Name</th>
      <th>Variation</th>
      <th>Buy</th>
      <th>Sell</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  </table>
<br></br>
</div>

app/views/items/umbrella.html.erb
<h1>Wall Mounted Items</h1>

<div class="container">
<table id="wallitems-datatable" class="display table table-striped table-bordered" data-source="<%= umbrellas_path(format: :json) %>">

  <thead>
    <tr>
      <th>Expand</th>
      <th>Name</th>
      <th>Variation</th>
      <th>Buy</th>
      <th>Sell</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  </table>
<br></br>
</div>

app/views/items/wall_mounted.html.erb
<h1>Wall Mounted Items</h1>

<div class="container">
<table id="wallitems-datatable" class="display table table-striped table-bordered" data-source="<%= wall_mounted_path(category: "wallpapers", format: :json) %>">

  <thead>
    <tr>
      <th>Expand</th>
      <th>Name</th>
      <th>Variation</th>
      <th>Buy</th>
      <th>Sell</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  </table>
<br></br>
</div>

app/views/items/wallpaper.html.erb
<h1>Wall Mounted Items</h1>

<div class="container">
<table id="wallitems-datatable" class="display table table-striped table-bordered" data-source="<%= wallpapers_path(format: :json) %>">

  <thead>
    <tr>
      <th>Expand</th>
      <th>Name</th>
      <th>Variation</th>
      <th>Buy</th>
      <th>Sell</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  </table>
<br></br>
</div>